assignment1/assignment1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("task.urls")),
    path('orm/', include("Orm_practice.urls")),
    path('demo/', include("demoapp.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

assignment1/task/urls.py
from django.urls import path, include
from .import views


urlpatterns = [
    path("", views.home, name='home'),
    path("login/", views.login_view, name='login'),
    path("log_out/", views.log_out, name='log_out'),
    path("create_task/", views.create_task, name='create_task'),
    path("add_sub_task/", views.add_sub_task, name='add_sub_task'),
    path("task_list/", views.task_list, name='task_list'),
    # path("create_task/", views.create_task, name='create_task'),
    path("task_detail/<int:pk>", views.task_detail, name='task_detail'),
    path('edit_task/<int:pk>', views.edit_task, name='edit_task'),
    path('delete_task/<int:pk>', views.delete_task, name='delete_task'),

]

assignment1/task/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    task_name = models.CharField(max_length=100)
    STATUS_CHOICES = (
        (1, 'Not Started'),
        (2, 'In Progress'),
        (3, 'Completed'),
    )
    Status = models.IntegerField(choices=STATUS_CHOICES)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return self.task_name


class SubtaskModel(models.Model):
    subtask_name = models.CharField(max_length=100)
    task_id = models.ForeignKey(Task, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.subtask_name

assignment1/task/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import Task, SubtaskModel


class loginform(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task_name', 'Status', 'owner']


class SubTaskForm(forms.ModelForm):
    class Meta:
        model = SubtaskModel
        fields = ['subtask_name', 'task_id']

assignment1/task/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .forms import TaskForm, SubTaskForm, loginform
from django.contrib.auth import login, logout, authenticate
from .models import Task, SubtaskModel, Task
from rest_framework.response import Response
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# from django.contrib.auth.middleware import AuthenticationMiddleware
# Create your views here.


def home(request):
    return render(request, 'home.html')


def login_view(request):
    if request.method == 'GET':
        form = loginform()
        return render(request, 'login.html', {'form': form})

    if request.method == 'POST':
        print('You are in post of login')
        form = loginform(request.POST, data=request.POST)
        if form.is_valid():
            print('Validated')
            uname = form.cleaned_data['username']
            pword = form.cleaned_data['password']
            user = authenticate(username=uname, password=pword)
            print(user)
            if user is not None:
                login(request, user)
                print('user logged in')
                return redirect('task_list')
            return redirect('home')
        return redirect('home')


@login_required
def create_task(request):
    if request.method == 'GET':
        form = TaskForm()
        return render(request, 'create_task.html', {'form': form})

    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('task_list')


@login_required
def task_detail(request, pk):
    if request.method == 'GET':
        task_data = Task.objects.get(id=pk)
        print(task_data)
        sub_task_data = SubtaskModel.objects.filter(task_id=pk)
        sub_task_form = SubTaskForm()
        return render(request, 'task_detail.html', {'data': sub_task_form, 'sub_task_data': sub_task_data, 'task_data': task_data})


@login_required
def task_list(request):
    if request.user.is_authenticated:
        task = Task.objects.filter(owner=request.user.id)
        return render(request, 'task_list.html', {'tasks': task})
    else:
        return HttpResponse('You are not allowed to enter here.')


def log_out(request):
    if request.method == 'GET':
        logout(request)
        messages.warning(request, 'logged out successfuly !!!')
        return redirect('home')


@login_required
def add_sub_task(request):
    if request.method == 'POST':
        form = SubTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('task_list')


@login_required
def delete_task(request, pk):
    data = Task.objects.get(id=pk)
    print(data)
    data.delete()
    return redirect('task_list')


@login_required
def edit_task(request, pk):
    if request.method == 'GET':
        status = Task.STATUS_CHOICES
        print(status)
        task = Task.objects.get(id=pk)
        print(task)
        return render(request, 'edit_task.html', {'status': status, 'task': task})

    if request.method == 'POST':
        tname = request.POST['task_name']
        sname = request.POST['Status']
        print(sname)
        current_user = User.objects.get(id=request.user.id)
        owner = request.user.id
        user = Task.objects.get(id=pk)
        user.task_name = tname
        user.Status = sname
        user.owner = current_user
        user.save()
        return redirect('task_list')

assignment1/task/templates/base_index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    {% block title %}
    {% endblock %}

</head>

<body>
    {% include 'navbar.html' %}
    {% block body %}
    {% endblock %}
</body>

</html>

assignment1/task/templates/create_task.html
{% extends 'base_index.html' %}

{% block body %}


<body style="text-align: center;background-color: darkgray;">
    <h1 style="background-color: aqua;">TASK MANAGER</h1>
    <h2>Create New Task</h2>
    <div>
        <form action="{% url 'create_task' %}" method="post">
            {% csrf_token %}
            {% for fm in form %}
            <div style="margin-bottom: 50px;">
                {{fm.label}} : {{fm}}
            </div>
            {% endfor %}

            <button type="submit">SUBMIT</button>
            <button type="reset">RESET</button>
        </form>
    </div>
</body>

{% endblock %}

assignment1/task/templates/edit_task.html
{% extends 'base_index.html' %}

{% block body %}

<body style="text-align: center;background-color: lightgray;">
    <h1 style="background-color: aqua;">TASK MANAGER</h1>
    <div>
        <form action="{% url 'edit_task' task.id %}" method="post">
            {% csrf_token %}

            <h1>EDIT TASK</h1>

            <label for="task_name">Task name : </label>
            <input type="text" name="task_name" id="task_name" value="{{task.task_name}}"><br>

            <label for="Status"></label>status :
            <select name="Status" id="Status">

                <option value="">SELECT</option>
                <option value="1">Not Started</option>
                <option value="2">In Progres</option>
                <option value="3">Completed</option>

            </select>

            <div>
                <button style="margin: 25px;" type="submit">SAVE</button>
                <button><a href="{% url 'task_detail' task.id %}">BACK</a></button>
            </div>
        </form>
    </div>

</body>

{% endblock %}

assignment1/task/templates/home.html
{% extends 'base_index.html' %}

{% block body %}


<body style="background-color:bisque;">

    <div style="text-align: center;">
        <h1 style="background-color: aqua;">Task Manager</h1>
        <h1>
            <!-- <marquee behavior="" direction="" style="background-color: aqua;">TASK MANAGER</marquee> -->
        </h1>
        <!-- <button type="submit">Login</button> -->
        <button><a style="text-decoration: none;" href="{% url 'login' %}">Login</a></button>
    </div>
    <div>
        <h4>Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia atque et eum reprehenderit tempora a
            commodi praesentium, corrupti est veniam beatae ullam exercitationem soluta perspiciatis dignissimos id
            saepe veritatis aspernatur iste facilis expedita vero. Ex cumque, dolores consequuntur facilis excepturi
            fugit aut, sit tempora placeat unde dicta quia vel hic commodi odio optio, explicabo animi quae doloribus
            voluptatum delectus voluptates corporis dolorem? Suscipit inventore accusantium alias consequuntur voluptas
            odio, hic et illum eum nihil, libero cum tenetur laborum sequi qui recusandae modi voluptatum est, eius ea!
            Magni molestias quaerat unde, repellat, cum porro aliquid nam commodi architecto, odio repellendus
            praesentium.</h4>

    </div>
    <div><img
            src="https://www.shutterstock.com/image-vector/business-planning-task-management-concept-600w-1987578881.jpg"
            alt="No Image" height="500px"></div>

    <!-- <marquee behavior="" direction="" style="background-color: aqua;">Sagar</marquee> -->

    <!-- <button><a href="http://127.0.0.1:5500/task/templates/login.html">Login</a></button> -->
</body>

{% endblock %}

assignment1/task/templates/login.html
<!-- <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LogIN</title>
</head> -->

{% extends 'base_index.html' %}

{% block body %}

<body style="background-color: lightgray;">
    <h1 style="text-align: center;background-color: aqua;">TASK MANAGER</h1>

</body>
<div style="text-align: center;">
    <!-- <h2>Form Content</h2> -->




    <div>


        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {% for u in form %}
            <div style="margin: 50px;">
                {{u.label}}:{{u}}
            </div>
            {% endfor %}

            <button type="submit">Login</button> &nbsp;&nbsp;
            <button><a style="text-decoration: none;" href="{% url 'home' %}">Back to Home</a></button>
        </form>
    </div>

</div>

<!-- </html> -->

{% endblock %}

assignment1/task/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li> -->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'log_out' %}">logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">login</a>
                </li>
                {% endif %}


            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

assignment1/task/templates/task_detail.html
{% extends 'base_index.html' %}

{% block body %}

<body style="background-color: lightgrey;text-align: center;">
    <h1 style="background-color: aqua;">TASK MANAGER</h1>

    <div>
        <h1>TASK INFORMATION</h1>
        <div>
            <p>TASK NAME:{{task_data.task_name}}</p>
            <p> TASK ID:{{task_data.id}}</p>
            <p> TASK STATUS:{{task_data.get_Status_display}}</p>

            <div style="margin: 35px;">
                <button><a href="{% url 'edit_task' task_data.id %}">EDIT</a></button>
                <button><a style="text-decoration: none;"
                        href="{% url 'delete_task' task_data.id %}">DELETE</a></button>
                <button><a style="text-decoration: none;" href="{% url 'task_list' %}">BACK</a></button>
            </div>

        </div>

    </div>



    <div>


        <h1>SUB TASK:</h1>
        <div>

            {% for k in sub_task_data %}

            <div>
                {{k}}
            </div>

            {% endfor %}

        </div>







    </div>

    <div style="margin: 50px;">
        <form action="{% url 'add_sub_task' %}" method="post">
            {% csrf_token %}
            {% for i in data %}
            <div style="margin-bottom: 50px;">
                {{i.label}} : {{i}}
            </div>
            {% endfor %}

            <button type="submit">submit</button>

        </form>

    </div>

    <div>
    </div>




</body>

{% endblock %}

assignment1/task/templates/task_list.html
{% extends 'base_index.html' %}

{% block body %}



<body style="text-align: center; background-color: darkgray;">
    <h1 style="background-color: aquamarine;">TASK MANAGER</h1>
    <button><a style="text-decoration: none;" href="{% url 'create_task' %}">Create</a></button>
    <button><a style="text-decoration: none;" href="">Status</a></button>
    <div>
        {% for w in tasks %}
        <div style="margin: 50px;">
            <a href="{% url 'task_detail' w.id %}">{{w}}</a>
        </div>

    </div>
    {% endfor %}
    <button><a style="text-decoration: none;" href="{% url 'login' %}">Previous</a></button>
    <button type="submit"><a style="text-decoration: none;" href="">Next</a></button>
</body>

{% endblock %}